name: publish
on:
  push:
    branches:
      - 'main'
jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the timescale image
      working-directory: ./timescale
      run: docker build . --tag timescale:pg13-latest
    - name: Build the timescale-mongofdw image
      working-directory: ./timescale-mongofdw
      run: docker build . --tag timescale-mongofdw:pg13-latest
    - name: Tag images for release
      run: |
        docker tag timescale:pg13-latest ghcr.io/jobgetapp/timescale:pg13-latest
        docker tag timescale-mongofdw:pg13-latest ghcr.io/jobgetapp/timescale-mongofdw:pg13-latest
    - name: Publish images
      run: |
        docker push ghcr.io/jobgetapp/timescale:pg13-latest
        docker push ghcr.io/jobgetapp/timescale-mongofdw:pg13-latest
